config/routes.rb
Rails.application.routes.draw do
  root 'memos#index'
  resources :memos

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
    def index
        SampleWorker.perform_async('aaa')
        @memos = Memo.all
        @memo = Memo.new
    end

    def create 
        SampleWorker.perform_async('aaa')
        @memo  = Memo.create(memo_params)
        p @memo.id
        redirect_to edit_memo_path(@memo)
    end

    def edit
        @memos = Memo.all
        @memo_new = Memo.new
        @memo = Memo.find(params[:id])
    end

    def update
        SampleWorker.perform_async('aaa')
        UpdateWorker.perform_async(params[:id],memo_params[:title],memo_params[:text])
    end

    def destroy
        @memo = Memo.find(params[:id])
        @memo.destroy
        redirect_to memos_path
    end

    private
        def memo_params
            params.require(:memo).permit(:title,:text)
        end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def index
        SampleWorker.perform_async("aaa")
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkerApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/memos/edit.html.erb
<div class="memos">
    <ul>
        <li class="memo_create">
            <%= form_for(@memo_new) do |f| %>
                <div><%= f.text_field :title, class: "add_text", :placeholder => "タイトル" %><%= f.submit '追加', class: "add_submit" %></div>
            <% end %>
        </li>
        <% @memos.each do |memo| %>
            <% if memo.id != @memo.id %>
                <li>
                    <div class="memos_title"><%= memo.title %><%= link_to '', edit_memo_path(memo) %></div>
                </li>
            <% else %>
                <li class="edit_li"> 
                    <div class="memos_delete"><%= link_to '削除', memo_path(memo), method: :delete %></div>
                    <div class="memos_title"><%= memo.title %></div>
                </li>
            <% end %>
        <% end %>
        
    </ul>
</div>
<div class="memo_edit">
    <%= form_for(@memo) do |f| %>
        <div class="memo_title"><%= f.submit '保存', class: "m_submit"%><%= f.text_field :title, class: "m_title" %></div>
        <div><%= f.text_area :text, class: "m_text" %></div>
    <% end %>
</div>

app/views/memos/index.html.erb
<div class="memos">
    <ul>
        <li class="memo_create">
            <%= form_for(@memo) do |f| %>
                <div><%= f.text_field :title, class: "add_text", :placeholder => "タイトル" %><%= f.submit '追加', class: "add_submit" %></div>
            <% end %>
        </li>
        <% @memos.each do |memo| %>
            <li>
                <div class="memos_title"><%= memo.title %><%= link_to '', edit_memo_path(memo) %></div>
            </li>
        <% end %>
        
    </ul>
</div>

app/views/static_pages/index.html.erb
<h1>おはよう</h1>